# Generated by Django 4.1 on 2023-09-03 18:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0002_remove_intern_id_intern_internid'),
        ('jobs', '0002_alter_job_company_alter_job_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('applicationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interns.intern')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'verbose_name': 'JobApplication',
                'verbose_name_plural': 'JobApplications',
                'db_table': 'JobApplications',
                'ordering': ['-createdAt'],
            },
        ),
    ]
