# Generated by Django 4.1 on 2023-09-01 11:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('employees', models.IntegerField()),
                ('established', models.IntegerField()),
                ('isActive', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('isPremium', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('recruiter', models.ForeignKey(db_column='recruiterId', on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='recruiters.recruiter')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'Companies',
                'ordering': ['createdAt'],
            },
        ),
    ]
