# Generated by Django 4.1 on 2023-08-31 22:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='id',
        ),
        migrations.AddField(
            model_name='intern',
            name='internId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
